version: '2'
services:

    db:
      image: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_DATABASE: frequency_occurence
      networks:
        - main

    web:
      restart: always
      image: aisangam/count_words_flask:first_commit
      command:  python3 manage.py
      ports:
        - "2226:5000"
      links:
        - db
      depends_on:
        - db
      networks:
        - main

networks:
  main:
    driver: bridge

volumes:
  scan_file:
